# Generated by Django 5.1.7 on 2025-03-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='Surname', max_length=30),
            preserve_default=False,
        ),
    ]
