# Generated by Django 5.1.7 on 2025-03-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_alter_contact_phone_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='members',
            new_name='contactids',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='join.task'),
        ),
    ]
