# Generated by Django 5.1.7 on 2025-03-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_rename_members_task_contactids_remove_task_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'urgent'), ('medium', 'medium'), ('low', 'low')], max_length=30),
        ),
    ]
