# Generated by Django 5.1.7 on 2025-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('todo', 'ToDo'), ('inprogress', 'In Progress'), ('awaitfeedback', 'Await Feedback'), ('done', 'Done')], default='todo', max_length=30),
        ),
    ]
