# Generated by Django 5.1.7 on 2025-03-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0012_remove_task_subtasks_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contactids',
            field=models.ManyToManyField(blank=True, to='join.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
