# Generated by Django 5.0.7 on 2025-03-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0013_alter_subtask_parent_alter_task_contactids_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
